/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.ListaPacientes;
import main.Paciente;

/**
 *
 * @author El_Sanster
 */
public class AgregarPaciente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarPaciente.class.getName());

    static ListaPacientes listaPacientes;
    static private MenuPrincipalGrafica ventanaPadre;
    /**
     * Creates new form AgregarPaciente
     */
    public AgregarPaciente(ListaPacientes listapacientes, MenuPrincipalGrafica padre) {
        initComponents();
        this.ventanaPadre = padre;
        this.listaPacientes = listapacientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Title = new javax.swing.JLabel();
        LB_NombrePaciente = new javax.swing.JLabel();
        LB_ID = new javax.swing.JLabel();
        LB_EPS = new javax.swing.JLabel();
        LB_FechaNacimiento = new javax.swing.JLabel();
        BTN_Aceptar = new javax.swing.JButton();
        BTN_Cancelar = new javax.swing.JButton();
        TF_Nombre = new javax.swing.JTextField();
        TF_EPS = new javax.swing.JTextField();
        TF_FormattedID = new javax.swing.JFormattedTextField();
        TF_FormattedFechaNacimiento = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LB_Title.setText("Gestion Hospitalaria - Agregar Paciente");

        LB_NombrePaciente.setText("Nombre del Paciente");

        LB_ID.setText("ID");

        LB_EPS.setText("EPS");

        LB_FechaNacimiento.setText("Fecha de Nacimiento");

        BTN_Aceptar.setText("Agregar");
        BTN_Aceptar.addActionListener(this::BTN_AceptarActionPerformed);

        BTN_Cancelar.setText("Cancelar");
        BTN_Cancelar.addActionListener(this::BTN_CancelarActionPerformed);

        TF_Nombre.setText("Nombre");

        TF_EPS.setText("EPS");

        TF_FormattedID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        TF_FormattedFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y-MM-d"))));
        TF_FormattedFechaNacimiento.setText("1998-12-31");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_EPS)
                            .addComponent(LB_FechaNacimiento))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTN_Aceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN_Cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(TF_FormattedFechaNacimiento))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_NombrePaciente)
                            .addComponent(LB_ID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TF_EPS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(TF_Nombre)
                            .addComponent(TF_FormattedID))))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addComponent(LB_Title)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_Title)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_NombrePaciente)
                    .addComponent(TF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_ID)
                    .addComponent(TF_FormattedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_EPS)
                    .addComponent(TF_EPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_FechaNacimiento)
                    .addComponent(TF_FormattedFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Aceptar)
                    .addComponent(BTN_Cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AceptarActionPerformed
        try {
            int id = Integer.parseInt(TF_FormattedID.getText());
           
            String nombre  = TF_Nombre.getText();
            String eps = TF_EPS.getText();
            
            LocalDate fechNac = LocalDate.parse(TF_FormattedFechaNacimiento.getText());
            
            listaPacientes.insertarPacienteEnGrafo(new Paciente(nombre, eps, fechNac, id));            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "El ID debe ser un número entero", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (java.time.format.DateTimeParseException e){
            JOptionPane.showMessageDialog(rootPane, "Formato de Fecha inválido", "Error", JOptionPane.ERROR_MESSAGE);
        }
        JOptionPane.showMessageDialog(rootPane, "Paciente añadido Correctamente");
        ventanaPadre.actualizarListaPacientes();
        this.dispose();
    }//GEN-LAST:event_BTN_AceptarActionPerformed

    private void BTN_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BTN_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        if (listaPacientes == null) {
            System.out.println("[INFO]: Detectada la ejecución desde MenuPrincipalGrafica, llamando a Menu Inicio Grafica\nDe preferencia iniciar el programa desde MenuInicioGrafica");
            MenuInicioGrafica xd = new MenuInicioGrafica();
            xd.setVisible(true);
            return;
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgregarPaciente(listaPacientes, ventanaPadre).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Aceptar;
    private javax.swing.JButton BTN_Cancelar;
    private javax.swing.JLabel LB_EPS;
    private javax.swing.JLabel LB_FechaNacimiento;
    private javax.swing.JLabel LB_ID;
    private javax.swing.JLabel LB_NombrePaciente;
    private javax.swing.JLabel LB_Title;
    private javax.swing.JTextField TF_EPS;
    private javax.swing.JFormattedTextField TF_FormattedFechaNacimiento;
    private javax.swing.JFormattedTextField TF_FormattedID;
    private javax.swing.JTextField TF_Nombre;
    // End of variables declaration//GEN-END:variables
}

