/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.ListaPacientes;

/**
 *
 * @author elsanster
 */
public class DatosRuta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatosRuta.class.getName());
    
    
    static private JFrame ventanaPadre;
    static ListaPacientes listaPacientes;
    /**
     * Creates new form DatosRuta
     */
    public DatosRuta(ListaPacientes listaPacientes, JFrame padre) {
        initComponents();
        this.ventanaPadre = padre;
        this.listaPacientes = listaPacientes;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_title = new javax.swing.JLabel();
        CB_SedeOrigen = new javax.swing.JComboBox<>();
        LB_SedeOrigen = new javax.swing.JLabel();
        LB_SedeDestino = new javax.swing.JLabel();
        CB_SedeDestino = new javax.swing.JComboBox<>();
        BTN_Calcular = new javax.swing.JButton();
        BTN_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LB_title.setText("Calcular Ruta - Gestion Hospitalaria");

        CB_SedeOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospital Central", "Clinica Norte", "Puesto de Salud Oriente", "Unidad medica sur" }));

        LB_SedeOrigen.setText("Sede Origen");

        LB_SedeDestino.setText("Sede Destino");

        CB_SedeDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospital Central", "Clinica Norte", "Puesto de salud Oriente", "Unidad medica sur" }));

        BTN_Calcular.setText("Calcular");
        BTN_Calcular.addActionListener(this::BTN_CalcularActionPerformed);

        BTN_Cancelar.setText("Cancelar");
        BTN_Cancelar.addActionListener(this::BTN_CancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_Calcular))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LB_title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_SedeOrigen)
                            .addComponent(LB_SedeDestino))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_SedeDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_SedeOrigen, 0, 205, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_SedeOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_SedeOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_SedeDestino)
                    .addComponent(CB_SedeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Calcular)
                    .addComponent(BTN_Cancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BTN_CancelarActionPerformed

    private void BTN_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CalcularActionPerformed
        listaPacientes.getRedEps().calcularRutaMasCorta((String) CB_SedeOrigen.getSelectedItem(),(String) CB_SedeDestino.getSelectedItem(), this);
        
    }//GEN-LAST:event_BTN_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        if (listaPacientes == null) {
            System.out.println("[INFO]: Detectada la ejecución desde MenuPrincipalGrafica, llamando a Menu Inicio Grafica\nDe preferencia iniciar el programa desde MenuInicioGrafica");
            MenuInicioGrafica xd = new MenuInicioGrafica();
            xd.setVisible(true);
            return;
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DatosRuta(listaPacientes, ventanaPadre).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Calcular;
    private javax.swing.JButton BTN_Cancelar;
    private javax.swing.JComboBox<String> CB_SedeDestino;
    private javax.swing.JComboBox<String> CB_SedeOrigen;
    private javax.swing.JLabel LB_SedeDestino;
    private javax.swing.JLabel LB_SedeOrigen;
    private javax.swing.JLabel LB_title;
    // End of variables declaration//GEN-END:variables
}
