/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author elsanster
 */
public class MenuInicioGrafica extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicioGrafica.class.getName());

    /**
     * Creates new form Principal
     */
    public MenuInicioGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Title = new javax.swing.JLabel();
        TF_FileName = new javax.swing.JTextField();
        LB_IngreseFilename = new javax.swing.JLabel();
        BTN_ExaminarFilename = new javax.swing.JButton();
        BTN_AbrirArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LB_Title.setText("Abrir Lista de Pacientes - Gestión Hospitalaria");

        TF_FileName.setText("datos.csv");

        LB_IngreseFilename.setText("Ingrese nombre del archivo, o su ruta de acceso:");

        BTN_ExaminarFilename.setText("Examinar");
        BTN_ExaminarFilename.addActionListener(this::BTN_ExaminarFilenameActionPerformed);

        BTN_AbrirArchivo.setText("Abrir Archivo");
        BTN_AbrirArchivo.addActionListener(this::BTN_AbrirArchivoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTN_AbrirArchivo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LB_IngreseFilename)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TF_FileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_ExaminarFilename)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(LB_Title)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB_IngreseFilename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_FileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_ExaminarFilename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_AbrirArchivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Al Seleccionar el botón de examinar, para generar la ventana de selección de archivos de forma nativa
    private void BTN_ExaminarFilenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ExaminarFilenameActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);

        // Obtener nombre de archivo al seleccionar el mismo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            // Reflejar nombre de archivo en el Campo de texto
            TF_FileName.setText(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_BTN_ExaminarFilenameActionPerformed

    private void BTN_AbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AbrirArchivoActionPerformed
        System.out.println("Info: Nombre de archivo seleccionado: " + TF_FileName.getText() + ", Intentando abrir archivo y inicializar menú principal");
        // Verificar input

        String filename = TF_FileName.getText();

        // En caso de nombre de archivo vacio no proceder
        if (filename.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese el archivo de la lista de pacientes (.csv)", "Error: Nombre del archivo vacío", JOptionPane.ERROR_MESSAGE);
            return;
        } 

        if (filename.toLowerCase().endsWith(".csv")) {
            filename += ".csv";
        }

        //Creamos el archivo .csv si no existe 
        File archivo = new File(filename);
        if (!archivo.exists()) {
            String [] options = {"Crear Nuevo Archivo", "Cancelar"};
            int op = JOptionPane.showOptionDialog(rootPane, "Quieres crear un nuevo archivo? (Archivo no encontrado)", "Archivo no encontrado", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            
            //En caso de cancelar o cerrar ventana no proceder
            if (op ==  -1 || op == 1){
                return;
            }
            
            try {
                if (archivo.createNewFile()) {
                    JOptionPane.showMessageDialog(rootPane, "Archivo creado Correctamente");
                    MenuPrincipalGrafica pr = new MenuPrincipalGrafica();
                    pr.setVisible(true);
                    this.setVisible(false);
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(rootPane, "No se pudo crear el archivo "+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                filename = "";
            }
        } else {
            MenuPrincipalGrafica pr = new MenuPrincipalGrafica();
            pr.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BTN_AbrirArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuInicioGrafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_AbrirArchivo;
    private javax.swing.JButton BTN_ExaminarFilename;
    private javax.swing.JLabel LB_IngreseFilename;
    private javax.swing.JLabel LB_Title;
    private javax.swing.JTextField TF_FileName;
    // End of variables declaration//GEN-END:variables
}
